"$schema" = "./node_modules/wrangler/config-schema.json"

name = "codex-auth-json-fetcher"
main = "src/index.js"
compatibility_date = "2026-04-09"
keep_vars = true

[assets]
binding = "ASSETS"
directory = "./public"
